### ISSUE TITLE
Hot reload support for .NET 6+ apps?

### ISSUE THREAD

**Issue by Meligy** [murugaratham/vscode-dotnet-watch#5]
Hello,
First, thanks heaps for the super awesome extension that fulfils a very common need, and for making it available for free.

I installed the extension and used it for my .NET 6 web app. It's very nice to see the debugger finally automagically attaches to the restarted .NET application.

However, I noticed that the app seems to restart for any kind of change. I don't know if it's just me imagining it to be honest or there's no hot reload support in the extension. Is it supposed to use hot reload?

**Comment by murugaratham** [comment]
Sadly no, see https://github.com/dotnet/runtime/issues/12409 and https://github.com/OmniSharp/omnisharp-vscode/issues/490

enc apparently has some proprietary stuff in it and msft kept it on visual studio only, from what I’ve read so far, it’s due to legacy and complexity that’s blocking it as .. 

Jetbrains rider does support hot reload somehow, but not sure how they are implementing it. 

Being a react developer, I use vscode personally day to day and want to use vs code as my main editor for both c# & react. Comparing frontend dev tools, hot reload on .net is still inferior to frontend or even springboot/golang.

what this extension does is to at least save developers time from manually restarting/stop-start debugging sessions by using dotnet watch

**Comment by Meligy** [comment]
Does the extension do anything to restart the app though or just leaves it to dotnet watch?

Because hot reload seems to work fine for me on the Mac terminal. That's how I use it most of the time, as I usually only need debug mode when actually debugging an issue.

My hypothesis is that if the extension restarts the app, then maybe the fix is for the extension do do nothing, and then it should in theory work the same as it does in the terminal (so would hot reload).

But if the extension already does nothing to restart the app, then this hypotheses is invalid.

**Comment by murugaratham** [comment]
Everytime a code change is detected when saving any file under .csproj, dotnet watch actually terminates it automatically (out of extensions control), what we do here when u run the debugger; is to generate a task, execute it and getting the the process id via a task definition match, then start a debug session automagically (via a setInterval timer every second) and of course killing the watch task when user decides to stop the debug session using 

debug.onDidTerminateDebugSession(DebuggerService.TryToRemoveDisconnectedDebugSession);

**Comment by Meligy** [comment]
Interesting. Makes you wonder why hot reload works in the console but not in this case!

**Comment by murugaratham** [comment]
Can I also assume that when u launch via console, you don’t have debugger attached, coz u do, it should detach whenever you save as well

**Comment by Meligy** [comment]
I don't yeah. That might be the difference.

Also working on a API+react project here as well BTW.

**Comment by murugaratham** [comment]
Hope that msft invest some time into edit and continue/omnisharp for vscode, then I can remove this extension 😎

for now it’s serving my needs and improved my development loop.

**Comment by Meligy** [comment]
It certainly does. Thanks again for creating it. It makes things much smoother.
